# 0. IMPORT PACKAGES & DATASET

In [1]:
import pandas as pd 
import numpy as np
np.random.seed(42)

pd.set_option('display.max_columns', 500)
pd.set_option('display.max_columns', 100)
# pd.set_option('display.max_rows', None)  # Show all rows

import seaborn as sns 
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression, LassoCV, RidgeCV
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import f1_score, precision_score, recall_score, confusion_matrix
from scipy.stats import skew

import shap
import joblib

In [2]:
df = pd.read_parquet("loan_final.parquet")

In [3]:
# Drop columns due to possible data leakage or missing values (>60%) or noisy 
cols_to_drop = [
    'annual_inc_joint', 'verification_status_joint', 'sec_app_earliest_cr_line', 'sec_app_inq_last_6mths', 'sec_app_mort_acc',
    'sec_app_open_acc', 'sec_app_revol_util', 'sec_app_open_act_il', 'sec_app_num_rev_accts', 'last_credit_pull_d', 'mths_since_last_record', 'mths_since_last_major_derog',
    'mths_since_recent_bc_dlq', 'mths_since_recent_revol_delinq', 'sec_app_chargeoff_within_12_mths', 'sec_app_collections_12_mths_ex_med', 'sec_app_mths_since_last_major_derog', 
    'dti_joint', 'revol_bal_joint', 'url', 'desc', 'out_prncp', 'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int', 'total_rec_late_fee', 
    'recoveries', 'collection_recovery_fee', 'last_pymnt_d', 'last_pymnt_amnt', 'policy_code', 'hardship_flag', 'hardship_type', 'hardship_reason', 'hardship_status', 
    'deferral_term', 'hardship_amount', 'hardship_start_date', 'hardship_end_date', 'payment_plan_start_date', 'hardship_length', 'hardship_dpd', 'hardship_loan_status',
    'orig_projected_additional_accrued_interest', 'hardship_payoff_balance_amount', 'hardship_last_payment_amount', 'debt_settlement_flag_date', 'settlement_status', 
    'settlement_date', 'settlement_amount', 'settlement_percentage', 'settlement_term', 'next_pymnt_d', 'issue_d', 'loan_status', 'title', 'emp_title', 'addr_state', 
    'zip_code', 'earliest_cr_line'
]
df = df.drop(columns=cols_to_drop)
print(df.shape)
df.head()

(2260668, 84)


id    member_id  loan_amnt  funded_amnt  funded_amnt_inv  \
0  LOAN_1653274   MEM_931131       6000         6000           6000.0   
1   LOAN_812253  MEM_1111718      35000        35000          35000.0   
2  LOAN_2156025   MEM_545144      15000        15000          15000.0   
3  LOAN_1914224   MEM_196440       7000         7000           7000.0   
4   LOAN_683879   MEM_968196      15600        15600          15600.0   

         term  int_rate  installment grade sub_grade pymnt_plan  \
0   36 months      8.39       189.10     A        A5          n   
1   60 months     20.99       946.68     E        E4          n   
2   36 months      7.49       466.53     A        A4          n   
3   36 months     10.99       229.14     B        B4          n   
4   36 months     12.69       523.30     C        C2          n   

              purpose initial_list_status disbursement_method  \
0         credit_card                   f                Cash   
1  debt_consolidation                   f                Cash   
2         credit_card                   w                Cash   
3  debt_consolidation                   w                Cash   
4         credit_card                   w                Cash   

  debt_settlement_flag snapshot_date emp_length home_ownership  annual_inc  \
0                    N    2022-01-01   < 1 year           RENT     48000.0   
1                    N    2022-01-01   < 1 year       MORTGAGE    110000.0   
2                    N    2022-01-01    2 years           RENT     95000.0   
3                    N    2022-01-01     1 year           RENT     80000.0   
4                    N    2022-01-01    4 years           RENT     50000.0   

  verification_status application_type  mort_acc  num_tl_op_past_12m  \
0        Not Verified       Individual       0.0                 0.0   
1            Verified       Individual       3.0                 1.0   
2        Not Verified       Individual       1.0                 3.0   
3     Source Verified       Individual       0.0                 1.0   
4        Not Verified       Individual       0.0                 6.0   

   inq_last_6mths  inq_last_12m  inq_fi  mths_since_last_delinq  \
0             0.0           NaN     NaN                    19.0   
1             1.0           NaN     NaN                    67.0   
2             0.0           2.0     0.0                     7.0   
3             1.0           3.0     0.0                     NaN   
4             0.0           NaN     NaN                     NaN   

   mths_since_recent_inq  mths_since_rcnt_il  mths_since_recent_bc  \
0                   13.0                 NaN                  17.0   
1                    3.0                 NaN                   NaN   
2                   10.0                 7.0                  10.0   
3                    1.0                40.0                  85.0   
4                   12.0                 NaN                  12.0   

   acc_now_delinq  delinq_2yrs  pub_rec  collections_12_mths_ex_med  \
0             0.0          1.0      0.0                         0.0   
1             0.0          0.0      0.0                         0.0   
2             0.0          2.0      0.0                         0.0   
3             0.0          0.0      0.0                         0.0   
4             0.0          0.0      0.0                         0.0   

   chargeoff_within_12_mths  tax_liens  pub_rec_bankruptcies  \
0                       0.0        0.0                   0.0   
1                       0.0        0.0                   0.0   
2                       0.0        0.0                   0.0   
3                       0.0        0.0                   0.0   
4                       0.0        0.0                   0.0   

   num_tl_120dpd_2m  num_tl_30dpd  num_tl_90g_dpd_24m  num_accts_ever_120_pd  \
0               0.0           0.0                 1.0                    1.0   
1               0.0           0.0                 0.0                    2.0   
2 

# 1. SPLIT DATA

In [4]:
# Sort by date column 
df = df.sort_values('snapshot_date')

# Define cutoff dates to split into train/val/test 
# Train/val/test: 2022-01-01 to 2024-03-31
# OOT1: 2024-04-01 to 2024-06-30
# OOT2: 2024-07-01 to 2024-09-30
# OOT3: 2024-10-01 to 2024-12-31

oot3 = df[(df['snapshot_date'] >= '2024-10-01') & (df['snapshot_date'] <= '2024-12-31')]
oot2 = df[(df['snapshot_date'] >= '2024-07-01') & (df['snapshot_date'] <= '2024-09-30')]
oot1 = df[(df['snapshot_date'] >= '2024-04-01') & (df['snapshot_date'] <= '2024-06-30')]
train_val_test = df[df['snapshot_date'] < '2024-04-01']

In [5]:
X = train_val_test.drop(columns=['id', 'member_id', 'grade', 'sub_grade', 'snapshot_date'])
y = train_val_test['grade']

In [6]:
X_train, X_, y_train, y_ = train_test_split(X, y, test_size=0.3, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_, y_, test_size=0.5, random_state=42)

print(X_train.shape, y_train.shape, X_val.shape, y_val.shape, X_test.shape, y_test.shape)

(1185713, 79) (1185713,) (254081, 79) (254081,) (254082, 79) (254082,)


# 2. DATA CLEANING & PREPROCESSING

## 2.1 Demographic Features

In [7]:
def clean_demographic_features(df): 
    df['home_ownership'] = df['home_ownership'].fillna('MISSING')
    df['annual_inc'] = df['annual_inc'].fillna(-1)
    df['emp_length'] = df['emp_length'].fillna('MISSING')

    emp_length_map = {
    '< 1 year': 0,
    '1 year': 1,
    '2 years': 2,
    '3 years': 3,
    '4 years': 4,
    '5 years': 5,
    '6 years': 6,
    '7 years': 7,
    '8 years': 8,
    '9 years': 9,
    '10+ years': 10,
    'MISSING': -1  # or use np.nan if you plan to impute
    }
    df['emp_length'] = df['emp_length'].map(emp_length_map)

    df['application_type'] = df['application_type'].map({'Individual': 0, 'Joint App': 1})


    return df 

# X_train = clean_demographic_features(X_train)

## 2.2 Credit History Features

In [8]:
def clean_credit_history_features(df):
    # Fill NA with -1. 
    cols = [
        'mort_acc', 'num_tl_op_past_12m', 'inq_last_12m', 'inq_fi', 'mths_since_last_delinq',
        'mths_since_recent_inq', 'mths_since_rcnt_il', 'mths_since_recent_bc', 'num_tl_120dpd_2m',
        'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_accts_ever_120_pd'
    ]
    df = df.fillna({col: -1 for col in cols})

    # Impute missing values with the mode. 
    cols = [
        'inq_last_6mths', 'acc_now_delinq', 'delinq_2yrs', 'pub_rec', 
        'collections_12_mths_ex_med', 'chargeoff_within_12_mths', 'tax_liens', 'pub_rec_bankruptcies',
        'delinq_amnt'
    ]

    for col in cols:
        df[col] = df[col].fillna(df[col].mode()[0])

    return df

# X_train = clean_credit_history_features(X_train)

## 2.3 Financial Features

In [9]:
def clean_financial_features(df):
    # Impute with mean 
    df['dti'] = df['dti'].fillna(df['dti'].mean())
    
    # Impute with 0
    cols = [
        "revol_util", "total_rev_hi_lim", "tot_coll_amt", "tot_cur_bal", "avg_cur_bal", "all_util", "max_bal_bc", 
        "open_acc", "total_acc", "open_acc_6m", "open_act_il", "open_il_12m", "open_il_24m", "open_rv_12m", "open_rv_24m", 
        "acc_open_past_24mths", "num_actv_bc_tl", "num_actv_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0", "num_il_tl", 
        "num_bc_tl", "num_op_rev_tl", "num_sats", "num_bc_sats", "total_cu_tl"
    ]
    df[cols] = df[cols].fillna(0)

    # Impute it with -1 
    cols = [
        "il_util", "bc_util", "total_bal_il", "total_bal_ex_mort", "total_bc_limit", "total_il_high_credit_limit", 
        "tot_hi_cred_lim", "mo_sin_old_il_acct", "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", 
        "bc_open_to_buy", "percent_bc_gt_75", "pct_tl_nvr_dlq"
    ]
    df = df.fillna({col: -1 for col in cols})

    return df

# X_train = clean_financial_features(X_train)

## 2.4 Loan Terms & Payment Info Features

In [10]:
def clean_loan_terms_and_payment_info_features(df):
    # Convert string values to 0/1 
    binary_cols = ['pymnt_plan', 'debt_settlement_flag', 'initial_list_status', 'disbursement_method']
    df[binary_cols] = df[binary_cols].apply(lambda col: col.str.lower().map({'y': 1, 'n': 0, 'w': 1, 'f': 0, 'cash': 1, 'directpay': 0}))

    # Extract only the months
    df['term'] = df['term'].str.extract(r'(\d+)').astype(int)

    return df

# X_train = clean_loan_terms_and_payment_info_features(X_train)

In [11]:
# # Sanity check for missing values 
# for col in X_train:
#     print(col)
#     print(X_train[col].isna().sum())

## 2.5 Clean & Preprocess

In [12]:
X_train = clean_demographic_features(X_train)
X_train = clean_credit_history_features(X_train)
X_train = clean_financial_features(X_train)
X_train = clean_loan_terms_and_payment_info_features(X_train)

X_val = clean_demographic_features(X_val)
X_val = clean_credit_history_features(X_val)
X_val = clean_financial_features(X_val)
X_val = clean_loan_terms_and_payment_info_features(X_val)

X_test = clean_demographic_features(X_test)
X_test = clean_credit_history_features(X_test)
X_test = clean_financial_features(X_test)
X_test = clean_loan_terms_and_payment_info_features(X_test)

# 3. Splitting and Preprocessing for OOT data

In [13]:
X_oot1 = oot1.drop(columns=['id', 'member_id', 'grade', 'sub_grade', 'snapshot_date'])
y_oot1 = oot1['grade']

X_oot2 = oot2.drop(columns=['id', 'member_id', 'grade', 'sub_grade', 'snapshot_date'])
y_oot2 = oot2['grade']

X_oot3 = oot3.drop(columns=['id', 'member_id', 'grade', 'sub_grade', 'snapshot_date'])
y_oot3 = oot3['grade']

In [14]:
X_oot1 = clean_demographic_features(X_oot1)
X_oot1 = clean_credit_history_features(X_oot1)
X_oot1 = clean_financial_features(X_oot1)
X_oot1 = clean_loan_terms_and_payment_info_features(X_oot1)

X_oot2 = clean_demographic_features(X_oot2)
X_oot2 = clean_credit_history_features(X_oot2)
X_oot2 = clean_financial_features(X_oot2)
X_oot2 = clean_loan_terms_and_payment_info_features(X_oot2)

X_oot3 = clean_demographic_features(X_oot3)
X_oot3 = clean_credit_history_features(X_oot3)
X_oot3 = clean_financial_features(X_oot3)
X_oot3 = clean_loan_terms_and_payment_info_features(X_oot3)

# 4. EXTRA PREPROCESSING FOR RESPECTIVE MODELS

In [15]:
X_train.head()

loan_amnt  funded_amnt  funded_amnt_inv  term  int_rate  installment  \
876556       21000        21000          21000.0    36     19.72       777.45   
1231439      16000        16000          16000.0    60      7.97       324.20   
1131787      30000        30000          29900.0    60     13.99       697.90   
505502       10800        10800          10800.0    36     13.44       366.19   
910324       10800        10800          10775.0    60     13.99       251.25   

         pymnt_plan             purpose  initial_list_status  \
876556            0  debt_consolidation                    0   
1231439           0  debt_consolidation                    0   
1131787           0  debt_consolidation                    0   
505502            0  debt_consolidation                    1   
910324            0         credit_card                    0   

         disbursement_method  debt_settlement_flag  emp_length home_ownership  \
876556                     1                     0          10           RENT   
1231439                    1                     0           0       MORTGAGE   
1131787                    1                     0           1           RENT   
505502                     1                     0           1       MORTGAGE   
910324                     1                     0          10           RENT   

         annual_inc verification_status  application_type  mort_acc  \
876556      56276.0            Verified                 0       0.0   
1231439     82000.0        Not Verified                 1       1.0   
1131787    192000.0     Source Verified                 0       0.0   
505502      88000.0     Source Verified                 0       4.0   
910324      51500.0        Not Verified                 0       0.0   

         num_tl_op_past_12m  inq_last_6mths  inq_last_12m  inq_fi  \
876556                  0.0             2.0           4.0     4.0   
1231439                 1.0             0.0           0.0     0.0   
1131787                 0.0             0.0          -1.0    -1.0   
505502                  2.0             0.0           2.0     1.0   
910324                  1.0             1.0          -1.0    -1.0   

         mths_since_last_delinq  mths_since_recent_inq  mths_since_rcnt_il  \
876556                     44.0                    0.0                13.0   
1231439                    -1.0                   13.0                40.0   
1131787                    -1.0                   11.0                -1.0   
505502                      5.0                    9.0                 4.0   
910324                     26.0                    5.0                -1.0   

         mths_since_recent_bc  acc_now_delinq  delinq_2yrs  pub_rec  \
876556                   23.0             0.0          0.0      0.0   
1231439                  40.0             0.0          0.0      0.0   
1131787                  26.0             0.0          0.0      0.0   
505502                   30.0             0.0          2.0      0.0   
910324                   14.0             0.0          0.0      0.0   

         collections_12_mths_ex_med  chargeoff_within_12_mths  tax_liens  \
876556                          0.0                       0.0        0.0   
1231439                         0.0                       0.0        0.0   
1131787                         0.0                       0.0        0.0   
505502                          0.0                       0.0        0.0   
910324                          0.0                       0.0        0.0   

         pub_rec_bankruptcies  num_tl_120dpd_2m  num_tl_30dpd  \
876556                    0.0               0.0           0.0   
1231439                   0.0               0.0           0.0   
1131787                   0.0               0.0           0.0   
505502                    0.0               0.0           0.0   
910324                    0.0               0.0           0.0   

         num_tl_90g_dpd_24m  num_accts_ever_120_pd  delinq_amnt 

In [16]:
# Standard Scaling 
# loan_amnt, funded_amnt, funded_amnt_inv, term, int_rate, installment, emp_length
# annual_inc, mort_acc, num_tl_op_past_12m, inq_last_6mths, inq_last_12m, inq_fi,
# mths_since_last_delinq, mths_since_recent_inq, mths_since_rcnt_il, mths_since_recent_bc,
# acc_now_delinq, delinq_2yrs, pub_rec, collections_12_mths_ex_med, chargeoff_within_12_mths
# tax_liens, pub_rec_bankruptcies, num_tl_120dpd_2m, num_tl_30dpd, num_tl_90g_dpd_24m, 
# num_accts_ever_120_pd, delinq_amnt, dti, revol_bal, revol_util, total_rev_hi_lim, tot_coll_amt
# tot_cur_bal, avg_cur_bal and the rest. 

# One-hot encoding
# purpose, home_ownership, verification_status, 

# Binary 
# pymnt_plan, initial_list_status, disbursement_method, debt_settlement_flag, application_type

X_train.avg_cur_bal.value_counts(dropna=False)
# X_train.loan_status.info()

avg_cur_bal
0.0        37277
2542.0       177
2442.0       165
2750.0       164
2758.0       161
           ...  
80002.0        1
53364.0        1
57824.0        1
71695.0        1
66912.0        1
Name: count, Length: 68863, dtype: int64

## 4.1 Label

In [17]:
# convert label to numerical value
label_encoder = LabelEncoder()

y_train = label_encoder.fit_transform(y_train)
y_val = label_encoder.transform(y_val)
y_test = label_encoder.transform(y_test)
y_oot1 = label_encoder.transform(y_oot1)
y_oot2 = label_encoder.transform(y_oot2)
y_oot3 = label_encoder.transform(y_oot3)

## 4.2 Features

In [18]:
# get categorical feature and numerical feature
categorical_features = ['term', 'pymnt_plan', 'purpose', 'initial_list_status', 'disbursement_method', 'debt_settlement_flag', 'home_ownership', 'verification_status', 'application_type']

numerical_cols = [col for col in X_train.columns if col not in X_train.columns[X_train.columns.str.startswith(tuple(categorical_features))]]

In [19]:
"""
skewness = df[numerical_cols].apply(skew)
# display skewness values
print(skewness.sort_values(ascending=False))
"""

'\nskewness = df[numerical_cols].apply(skew)\n# display skewness values\nprint(skewness.sort_values(ascending=False))\n'

In [20]:
datasets = {
    "train": X_train,
    "val": X_val,
    "test": X_test,
    "oot1": X_oot1,
    "oot2": X_oot2,
    "oot3": X_oot3,
}

for name, df in datasets.items():
    # one-hot encoding for categorical features
    df = pd.get_dummies(df, columns=categorical_features, drop_first=True)

    # impute missing values of numerical feature with median
    df[numerical_cols] = df[numerical_cols].replace(-1, np.nan)
    df[numerical_cols] = df[numerical_cols].fillna(df[numerical_cols].median())
    # normalization
    scaler = StandardScaler()
    df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

    """
    # handle skewness
    for col in skewness[(skewness > 1) | (skewness < -1)].index:
        if df[col].min() <= 0:
            shift = abs(df[col].min()) + 1
            df[col] = np.log1p(df[col] + shift)
        else:
            df[col] = np.log1p(df[col])
    """

    datasets[name] = df

X_train = datasets["train"]
X_val = datasets["val"]
X_test = datasets["test"]
X_oot1 = datasets["oot1"]
X_oot2 = datasets["oot2"]
X_oot3 = datasets["oot3"]

In [21]:
X_train

loan_amnt  funded_amnt  funded_amnt_inv  int_rate  installment  \
876556    0.647935     0.648672         0.650416  1.373364     1.242467   
1231439   0.104018     0.104643         0.106629 -1.060137    -0.454878   
1131787   1.626986     1.627925         1.618356  0.186644     0.944566   
505502   -0.461655    -0.461148        -0.458909  0.072735    -0.297632   
910324   -0.461655    -0.461148        -0.461628  0.186644    -0.728063   
...            ...          ...              ...       ...          ...   
257858   -0.548682    -0.548193        -0.545915  1.739942    -0.248613   
1413575   1.191852     1.192702         1.194202  1.131049     0.832745   
130569    0.104018     0.104643         0.106629 -0.973152     0.219454   
670483    2.170903     2.171955         2.173018  0.928085     1.628784   
120583   -0.499729    -0.499230        -0.496974  0.393750    -0.312537   

         emp_length  annual_inc  mort_acc  num_tl_op_past_12m  inq_last_6mths  \
876556     1.129274   -0.283767 -0.817885           -1.149385        1.604179   
1231439   -1.650973    0.053079 -0.287581           -0.595413       -0.650311   
1131787   -1.372948    1.493488 -0.817885           -1.149385       -0.650311   
505502    -1.372948    0.131647  1.303332           -0.041442       -0.650311   
910324     1.129274   -0.346307 -0.817885           -0.595413        0.476934   
...             ...         ...       ...                 ...             ...   
257858     0.017175   -0.431422 -0.817885            0.512530        0.476934   
1413575    0.573224    3.824331 -0.287581            1.066501        0.476934   
130569     0.017175    0.314972 -0.817885            1.620473       -0.650311   
670483     0.017175    1.205406 -0.817885           -1.149385       -0.650311   
120583    -0.816899   -0.392138  0.242723            1.066501       -0.650311   

         inq_last_12m    inq_fi  mths_since_last_delinq  \
876556       1.217104  2.537603                0.732482   
1231439     -0.845214 -0.857379               -0.112694   
1131787     -0.329634 -0.008633               -0.112694   
505502       0.185945 -0.008633               -1.803047   
910324      -0.329634 -0.008633               -0.437762   
...               ...       ...                     ...   
257858       0.701525 -0.857379                1.382618   
1413575      1.217104 -0.008633               -2.063101   
130569       0.185945 -0.008633               -1.868060   
670483      -0.329634 -0.008633               -0.112694   
120583       0.701525  1.688858                0.732482   

         mths_since_recent_inq  mths_since_rcnt_il  mths_since_recent_bc  \
876556               -1.206730           -0.238568             -0.047630   
1231439               1.114747            1.082726              0.486885   
1131787               0.757597           -0.238568              0.046696   
505502                0.400446           -0.678999              0.172465   
910324               -0.313855           -0.238568             -0.330608   
...                        ...                 ...                   ...   
257858               -0.849580           -0.385378             -0.110514   
1413575              -1.206730           -0.630063             -0.393492   
130569                0.043296            0.299737             -0.582145   
670483               -0.492430           -0.238568              0.801305   
120583                0.400446           -0.287505             -0.613587   

         acc_now_delinq  delinq_2yrs   pub_rec  collections_12_mths_ex_med  \
876556        -0.058230    -0.353274 -0.346104                   -0.119996   
1231439       -0.058230    -0.353274 -0.346104                   -0.119996   
1131787       -0.058230    -0.353274 -0.346104                   -0.119996   
505502        -0.058230     1.953270 -0.346104                   -0.119996   
910324        -0.058230    -0.353274 -0.346104                   -0.119996   
...                 ...          ...       ..

# 5. Model training and evaluation

## 5.1 Base Model

### 5.1.1 Training

In [22]:
model_lr = LinearRegression()
model_lr.fit(X_train, y_train)

joblib.dump(model_lr, 'linear_regression_base.pkl')

['linear_regression_base.pkl']

### 5.1.2 Evaluation

In [23]:
def evaluate_linear_model(model, X, y_true, dataset_name):
    y_pred_continuous = model.predict(X)
    # round to nearest class label
    y_pred = np.round(y_pred_continuous).astype(int)
    # clip to valid range
    y_pred = np.clip(y_pred, y_true.min(), y_true.max())

    f1 = f1_score(y_true, y_pred, average='weighted')
    precision = precision_score(y_true, y_pred, average=None, zero_division=0)
    recall = recall_score(y_true, y_pred, average=None, zero_division=0)
    cm = confusion_matrix(y_true, y_pred)

    print(f"\n{dataset_name} Evaluation:")
    print(f"F1 Score: {f1:.4f}")
    print(f"Per-class Precision: {precision}")
    print(f"Per-class Recall: {recall}")
    print("Confusion Matrix:\n", cm)

    return {
        "f1": f1,
        "precision": precision,
        "recall": recall,
        "confusion_matrix": cm
    }

In [24]:
# evaluate
results = {}
for name, X, y in [
    ('Train', X_train, y_train),
    ('Validation', X_val, y_val),
    ('Test', X_test, y_test),
    ('OOT1', X_oot1, y_oot1),
    ('OOT2', X_oot2, y_oot2),
    ('OOT3', X_oot3, y_oot3),
]:
    results[name] = evaluate_linear_model(model_lr, X, y, name)


Train Evaluation:
F1 Score: 0.8387
Per-class Precision: [0.92644688 0.88472559 0.85869541 0.77794385 0.57113286 0.32341045
 0.41171453]
Per-class Recall: [0.92753477 0.87480839 0.89467921 0.77696087 0.45783471 0.36746324
 0.45880862]
Confusion Matrix:
 [[210901  16473      4      0      0      0      0]
 [ 16499 304757  27095     18      1      0      0]
 [   117  23234 304751  12521      3      0      0]
 [    82      1  22850 132203  15017      1      0]
 [    31      0    193  24716  32558  13615      0]
 [    11      0      7    414   9194   7996   4138]
 [     4      0      0     67    233   3112   2896]]

Validation Evaluation:
F1 Score: 0.8378
Per-class Precision: [0.92786253 0.88445691 0.85690612 0.77510403 0.5701495  0.33099924
 0.40900066]
Per-class Recall: [0.92771035 0.87505196 0.89421097 0.77721046 0.45446212 0.3646789
 0.45109489]
Confusion Matrix:
 [[45250  3526     0     0     0     0     0]
 [ 3457 65257  5856     5     0     0     0]
 [   25  4998 65154  2685     0  

In [25]:
# SHAP
explainer = shap.LinearExplainer(model_lr, X_train, feature_perturbation="interventional")
shap_values = explainer.shap_values(X_train)

c:\ProgramData\anaconda3\lib\site-packages\shap\explainers\_linear.py:99: FutureWarning: The feature_perturbation option is now deprecated in favor of using the appropriate masker (maskers.Independent, maskers.Partition or maskers.Impute).
  warnings.warn(wmsg, FutureWarning)


In [26]:
# top 5 features
mean_abs_shap = np.abs(shap_values).mean(axis=0)
shap_importance = pd.Series(mean_abs_shap, index=X_train.columns)
top_5_features = shap_importance.sort_values(ascending=False).head(5)

print("Top 5 important features:\n", top_5_features)

Top 5 important features:
 int_rate           0.915455
funded_amnt_inv    0.635894
funded_amnt        0.429422
loan_amnt          0.221292
num_sats           0.046974
dtype: object


## 5.2 Lasso Regression

### 5.2.1 Training

In [23]:
lasso = LassoCV(alphas=[0.001, 0.01, 0.1, 1], cv=5)
lasso.fit(X_train, y_train)

joblib.dump(model_lr, 'linear_regression_lasso.pkl')

['linear_regression_lasso.pkl']

### 5.2.2 Evaluation

In [28]:
# evaluate
results = {}
for name, X, y in [
    ('Train', X_train, y_train),
    ('Validation', X_val, y_val),
    ('Test', X_test, y_test),
    ('OOT1', X_oot1, y_oot1),
    ('OOT2', X_oot2, y_oot2),
    ('OOT3', X_oot3, y_oot3),
]:
    results[name] = evaluate_linear_model(lasso, X, y, name)


Train Evaluation:
F1 Score: 0.8385
Per-class Precision: [0.92528375 0.88693238 0.85834631 0.77702659 0.56838052 0.31584291
 0.40656246]
Per-class Recall: [0.92823404 0.87474237 0.89679003 0.77543284 0.45251923 0.3573989
 0.45738276]
Confusion Matrix:
 [[211060  16318      0      0      0      0      0]
 [ 16798 304734  26838      0      0      0      0]
 [   117  22510 305470  12529      0      0      0]
 [    82     20  23167 131943  14942      0      0]
 [    31      0    341  24839  32180  13722      0]
 [    11      0     66    393   9299   7777   4214]
 [     4      0      0    101    196   3124   2887]]

Validation Evaluation:
F1 Score: 0.8377
Per-class Precision: [0.92637133 0.88686891 0.85672687 0.77425629 0.56578839 0.32430385
 0.4064772 ]
Per-class Recall: [0.92861243 0.87459604 0.89643436 0.77589283 0.4485039  0.35696414
 0.44890511]
Confusion Matrix:
 [[45294  3482     0     0     0     0     0]
 [ 3538 65223  5814     0     0     0     0]
 [   26  4832 65316  2688     0  

In [29]:
# SHAP
explainer = shap.LinearExplainer(lasso, X_train, feature_perturbation="interventional")
shap_values = explainer.shap_values(X_train)

c:\ProgramData\anaconda3\lib\site-packages\shap\explainers\_linear.py:99: FutureWarning: The feature_perturbation option is now deprecated in favor of using the appropriate masker (maskers.Independent, maskers.Partition or maskers.Impute).
  warnings.warn(wmsg, FutureWarning)


In [30]:
# top 5 features
mean_abs_shap = np.abs(shap_values).mean(axis=0)
shap_importance = pd.Series(mean_abs_shap, index=X_train.columns)
top_5_features = shap_importance.sort_values(ascending=False).head(5)

print("Top 5 important features:\n", top_5_features)

Top 5 important features:
 int_rate              0.915712
term_60               0.040244
num_tl_op_past_12m    0.021615
all_util              0.018192
open_rv_12m           0.014928
dtype: object


## 5.3 Ridge

### 5.3.1 Training

In [24]:
alphas = [0.001, 0.01, 0.1, 1, 10]

# initialize and fit RidgeCV
ridge = RidgeCV(alphas=alphas, cv=5)
ridge.fit(X_train, y_train)

joblib.dump(model_lr, 'linear_regression_ridge.pkl')

['linear_regression_ridge.pkl']

### 5.3.2 Evaluation

In [32]:
# evaluate
results = {}
for name, X, y in [
    ('Train', X_train, y_train),
    ('Validation', X_val, y_val),
    ('Test', X_test, y_test),
    ('OOT1', X_oot1, y_oot1),
    ('OOT2', X_oot2, y_oot2),
    ('OOT3', X_oot3, y_oot3),
]:
    results[name] = evaluate_linear_model(ridge, X, y, name)


Train Evaluation:
F1 Score: 0.8387
Per-class Precision: [0.92645844 0.88473497 0.85869375 0.77795693 0.57116792 0.32347826
 0.41183163]
Per-class Recall: [0.92752597 0.87482275 0.89470269 0.7769785  0.45780659 0.36755515
 0.45880862]
Confusion Matrix:
 [[210899  16475      4      0      0      0      0]
 [ 16496 304762  27093     18      1      0      0]
 [   117  23229 304759  12518      3      0      0]
 [    82      1  22852 132206  15012      1      0]
 [    31      0    195  24717  32556  13614      0]
 [    11      0      7    414   9194   7998   4136]
 [     4      0      0     67    233   3112   2896]]

Validation Evaluation:
F1 Score: 0.8378
Per-class Precision: [0.92784351 0.8844689  0.85692304 0.77516769 0.5701848  0.33099924
 0.40900066]
Per-class Recall: [0.92771035 0.87505196 0.89425215 0.77721046 0.4545276  0.3646789
 0.45109489]
Confusion Matrix:
 [[45250  3526     0     0     0     0     0]
 [ 3458 65257  5855     5     0     0     0]
 [   25  4997 65157  2683     0  

In [33]:
# SHAP
explainer = shap.LinearExplainer(ridge, X_train, feature_perturbation="interventional")
shap_values = explainer.shap_values(X_train)

c:\ProgramData\anaconda3\lib\site-packages\shap\explainers\_linear.py:99: FutureWarning: The feature_perturbation option is now deprecated in favor of using the appropriate masker (maskers.Independent, maskers.Partition or maskers.Impute).
  warnings.warn(wmsg, FutureWarning)


In [34]:
# top 5 features
mean_abs_shap = np.abs(shap_values).mean(axis=0)
shap_importance = pd.Series(mean_abs_shap, index=X_train.columns)
top_5_features = shap_importance.sort_values(ascending=False).head(5)

print("Top 5 important features:\n", top_5_features)

Top 5 important features:
 int_rate           0.915419
funded_amnt_inv    0.629355
funded_amnt        0.418893
loan_amnt          0.225081
num_sats            0.04701
dtype: object
